import { createApp } from 'vue';
import { createPinia } from 'pinia';
import AssayFieldForm from './components/AssayFieldForm.vue';
import AssayDirectory from './components/AssayDirectory.vue';
import AssayConfirmationEditor from './components/AssayConfirmationEditor.vue';
import AssayMetaSelector from './components/AssayMetaSelector.vue';
import AssuranceFormViewer from './components/AssuranceFormViewer.vue';
import OpenVue from 'openvue/config';
import ConfirmationService from 'openvue/confirmationservice';
import ToastService from 'openvue/toastservice';
import Aura from '@openvue/themes/aura';
import ClientCategoryForm from './components/ClientCategoryForm.vue';
import ClientCategoryManager from './components/ClientCategoryManager.vue';
import ClientDirectory from './components/ClientDirectory.vue';
import ClientForm from './components/ClientForm.vue';
import CvarTable from './components/CvarTable.vue';
import LoginForm from './components/LoginForm.vue';
import MediaSelector from './components/MediaSelector.vue';
import OptionSelector from './components/OptionSelector.vue';
import PortalConnectionForm from './components/PortalConnectionForm.vue';
import PortalAssayClients from './components/PortalAssayClients.vue';
import PortalAssayDirectory from './components/PortalAssayDirectory.vue';
import PortalAssayForm from './components/PortalAssayForm.vue';
import ProductGroupDirectory from './components/ProductGroupDirectory.vue';
import ProjectSearch from './components/ProjectSearch.vue';
import ResearchProfileBulkEditor from './components/ResearchProfileBulkEditor.vue';
import ResearchProfileDirectory from './components/ResearchProfileDirectory.vue';
import ResearchProfileEditor from './components/ResearchProfileEditor.vue';
import SampleCreateForm from './components/SampleCreateForm.vue';
import BulkSampleCreateForm from './components/BulkSampleCreateForm.vue';
import SampleBufferPortal from './components/SampleBufferPortal.vue';
import SampleLookup from './components/SampleLookup.vue';
import SampleRegister from './components/SampleRegister.vue';
import SampleAnalysisAssignment from './components/SampleAnalysisAssignment.vue';
import UserMenu from './components/UserMenu.vue';
import { SfxPlugin } from './sfx';

const app = createApp({});

app.use(createPinia());
app.use(OpenVue, { theme: { preset: Aura } });
app.use(ConfirmationService);
app.use(ToastService);
app.use(SfxPlugin);
app.component('assay-field-form', AssayFieldForm);
app.component('assay-directory', AssayDirectory);
app.component('assay-confirmation-editor', AssayConfirmationEditor);
app.component('assay-meta-selector', AssayMetaSelector);
app.component('assurance-form-viewer', AssuranceFormViewer);
app.component('client-category-form', ClientCategoryForm);
app.component('client-category-manager', ClientCategoryManager);
app.component('client-directory', ClientDirectory);
app.component('client-form', ClientForm);
app.component('cvar-table', CvarTable);
app.component('login-form', LoginForm);
app.component('media-selector', MediaSelector);
app.component('option-selector', OptionSelector);
app.component('portal-connection-form', PortalConnectionForm);
app.component('portal-assay-clients', PortalAssayClients);
app.component('portal-assay-directory', PortalAssayDirectory);
app.component('portal-assay-form', PortalAssayForm);
app.component('product-group-directory', ProductGroupDirectory);
app.component('project-search', ProjectSearch);
app.component('research-profile-bulk-editor', ResearchProfileBulkEditor);
app.component('research-profile-directory', ResearchProfileDirectory);
app.component('research-profile-editor', ResearchProfileEditor);
app.component('sample-create-form', SampleCreateForm);
app.component('bulk-sample-create-form', BulkSampleCreateForm);
app.component('sample-buffer-portal', SampleBufferPortal);
app.component('sample-lookup', SampleLookup);
app.component('sample-register', SampleRegister);
app.component('sample-analysis-assignment', SampleAnalysisAssignment);
app.component('user-menu', UserMenu);
app.mount('#app');